# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'dna_blockchain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dna_blockchain
    pod 'AFNetworking', '~> 2.6'
  	pod 'ORStackView', '~> 3.0'
    pod 'ResearchKit', '~> 1.5'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
   # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  
  target 'dna_blockchainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
